### ISSUE TITLE
無法接收驗證簡訊

### ISSUE THREAD

**Issue by akio-bob** [wdzeng/bot-automation#10]
我一直收不到蝦皮的認證簡訊
如何解決呢？

**Comment by wdzeng** [comment]
我看了你的 log，發現機器人出 bug 了，感謝回報。

請問 12 次的狀況都是收不到蝦皮的認證簡訊嗎？

**Comment by akio-bob** [comment]
沒錯

**Comment by akio-bob** [comment]
> 我看了你的 log，發現機器人出 bug 了，感謝回報。
> 
> 請問 12 次的狀況都是收不到蝦皮的認證簡訊嗎？

沒有錯12次都是這樣

**Comment by akio-bob** [comment]
沒錯

hyperbola ***@***.***> 於 2022年6月19日 週日 15:23 寫道：

**Comment by wdzeng** [comment]
@akio-bob 你遇到的是錯誤代碼 4，這是最棘手的問題。我剛剛更新了機器人，請你再跑一次。沒意外的話，還是會失敗，但是我現在開始有記錄截圖，這樣會比較好除錯。

請依照以下方式下載截圖：

![image](https://user-images.githubusercontent.com/39057640/174472338-a0828cbe-7a93-4350-a929-438c842568c8.png)

![image](https://user-images.githubusercontent.com/39057640/174472361-369cb612-dea4-4443-bf65-85c960a1586b.png)

把下載的 zip 檔解壓縮，裡面有截圖。再麻煩你把那張截圖傳到這裡來。如果你擔心有隱私問題的話，也可以私傳給我。

**Comment by wdzeng** [comment]
@akio-bob 你的問題與 #8 雷同。我先把這個討論串關掉，再麻煩您接下來有問題的話再回覆於那個討論串囉！
