### ISSUE TITLE
Error code 5 以及支援電子郵件驗證

### ISSUE THREAD

**Issue by meateviler** [wdzeng/bot-automation#12]
請問 error code 5 是什麼意思？

**Comment by wdzeng** [comment]
你的帳號觸發電子郵件驗證而非手機簡訊驗證。很遺憾目前機器人不支援電子郵件驗證。

**Comment by ankle7766** [comment]
坐等解決方法........

**Comment by wdzeng** [comment]
@ankle7766 我目前卡在沒有能夠走信箱驗證的蝦皮帳號，這樣子要做測試實在是非常困難 ಥ_ಥ

**Comment by akio-bob** [comment]
> @ankle7766 我目前卡在沒有能夠走信箱驗證的蝦皮帳號，這樣子要做測試實在是非常困難 ಥ_ಥ

還是我可以借你看看我的蝦皮帳號 因為我的基本上都是觸發信箱驗證

**Comment by wdzeng** [comment]
Hi @ankle7766,

如果真的可以，我將萬分感謝。如果有需要，可以透過我的信箱 me@hyperbola.me 聯繫。

感恩！

**Comment by dearsiang** [comment]
也遇到無法電子郵件驗證

**Comment by wdzeng** [comment]
Hi @dearsiang,

抱歉，因為我沒辦法重現電子郵件驗證的情況，目前進度卡著。我自己的蝦皮帳號只會觸發簡訊驗證。

**Comment by akio-bob** [comment]
還是我借你我的蝦皮？

hyperbola ***@***.***> 於 2022年6月21日 週二 14:21 寫道：

**Comment by malenca88** [comment]
同樣問題... 猜是開始用蝦皮時，是用 email 認證，後來也有再新增手機驗證，但可能順序上還是 email 排在前

**Comment by HotdogWang** [comment]
更新一下我的解決方法
1. 進到帳戶設置裡面重新設置信箱，一樣的重複打也沒有關係，然後不要收認證信（雖然我到最後都沒有收到認證信）
2. 在帳戶設置裡面重新設置手機號碼，一樣的重複打也沒有關係，然後應該會認證密碼跟帳戶
3. 重新執行 workflow，應該就會成功了

思考的邏輯是先讓信箱失效，再成功認證手機號碼
果然就轉成用手機，現在還不確定的是信箱認證完後會不會改回信箱

最後感謝作者開發🙏

**Comment by wdzeng** [comment]
Hi @HotdogWang 這太強大了！置頂！

**Comment by enjiang0423** [comment]
與大家分享一下，
原先是用信箱驗證的，可以聯繫蝦皮客服改SMS驗證，就可以完成簡訊驗證了～～～
![Uploading 398DE6D6-E762-444D-B0D2-5FFE3446C223.png…]()

**Comment by wdzeng** [comment]
既然已經有兩位大大提供解方了，我就不做信箱驗證的功能囉。

我先關掉這個討論串。

**Comment by ankle7766** [comment]
今天用手機的sms簡訊登入蝦皮之後
run一遍機器人，是可以通過的
