### ISSUE TITLE
是否支援 Google 或臉書第三方登入

### ISSUE THREAD

**Issue by Shihwei0527** [wdzeng/bot-automation#14]
當初註冊的時候是直接選 facebook 登入，嘗試使用 facebook 的帳號密碼當參數，但一直顯示帳號密碼錯誤，請問目前是否沒有支援 facebook 登入，謝謝

**Comment by wdzeng** [comment]
您好，目前不支援第三方登入喔

**Comment by Shihwei0527** [comment]
好的，我再多試幾次看看，謝謝，因為昨天晚上連續 5 次都執行失敗

**Comment by ayugioh2003** [comment]
如果之前是用臉書登入、沒有設定密碼的話
可以用忘記密碼，然後設定蝦皮的密碼
之後就可以用這個密碼登入了
