### ISSUE TITLE
出現「抱歉，無法驗證您的身份，請您連繫...」錯誤訊息

### ISSUE THREAD

**Issue by jasperchang** [wdzeng/bot-automation#16]
Hi 開發者您好

機器人用了之後，第一、二次是因為密碼錯誤所以失敗，但後來更正後出現了 exit code 4。

看了 screenshot 後發現是會出現「抱歉，無法驗證您的身份，請您連繫 ... 」這個問題。

請問有什麼解決方法嗎？我的帳號是手機註冊的。

**Comment by wdzeng** [comment]
這個我也沒有辦法。可能是嘗試次數太多被 ban 的關係，明天試試看能不能囉 QAQ

**Comment by wdzeng** [comment]
@jasperchang 我記得蝦皮的帳號有需要身份認證的樣子，你的蝦皮帳號是新的嗎？

**Comment by jasperchang** [comment]
@wdzeng 是今天新建的沒錯

**Comment by wdzeng** [comment]
@jasperchang 那你可能要先手動完成手機綁定或信箱驗證之類的流程。Google Actions 登入時是用國外的 IP，我猜蝦皮把你的帳號當成假帳號了。

**Comment by jasperchang** [comment]
@wdzeng 已經有綁定手機且驗證好了，那我明天再試試吧

**Comment by wdzeng** [comment]
Hi @jasperchang,

你看起來已經成功簽到的樣子，我就先關閉這串囉！

**Comment by jasperchang** [comment]
@wdzeng 是的，已透過客服可成功登入了，非常感謝

**Comment by jpdakwind** [comment]
> @wdzeng 是的，已透過客服可成功登入了，非常感謝

請問您跟客服怎麼反應呢?

**Comment by jasperchang** [comment]
> > @wdzeng 是的，已透過客服可成功登入了，非常感謝
> 
> 請問您跟客服怎麼反應呢?

只是說無法登入，他就請我提供一些資料，確認是帳號所有人後，就開通簡訊認證，認證完就可登入了
