### ISSUE TITLE
如何更改排程時間？

### ISSUE THREAD

**Issue by eddiecykuo** [wdzeng/bot-automation#18]
請問是否可手動修改執行時間？

**Comment by williesmithchen** [comment]
https://github.com/wdzeng/bot-automation/blob/main/.github/workflows/shopee-checkin.yml#L8

**Comment by kai456789** [comment]
編輯 shopee-checkin.yml 裡面 這一行
  - cron:  '10 16 * * *'

**Comment by wdzeng** [comment]
注意時區是格林威治標準時間喔
