### ISSUE TITLE
【提示】一些對於使用 GitHub Actions 的提醒

### ISSUE THREAD

**Issue by 01101sam** [wdzeng/bot-automation#19]
由於 GitHub 的 [ToS](https://docs.github.com/en/site-policy/github-terms/github-terms-for-additional-products-and-features#actions) 中已明確表明不建議使用 GitHub Actions 作為自動簽到的操作，

所以請開發者在 README 中添加對程式使用而造成的限制列出，

以免後續有其他使用者過來詢問 GitHub 賬號被封禁的問題，

或者，以其他平台（比如 Azure Function、自己的機器、Cliudflare Workers）替代，

謝謝您的理解。

**Comment by wdzeng** [comment]
Hi @01101sam,

謝謝你的建議，我已經在[〈蝦皮簽到機器人使用說明〉](https://github.com/wdzeng/bot-automation/blob/main/docs/shopee-gha-inst.md)加上警語。另外我把這則 issue 置頂。

Thanks!

**Comment by 01101sam** [comment]
非常感謝！如無額外補充我將會關閉此 issue 以便後續方便維護，再次感謝您的回复。
