### ISSUE TITLE
Exit Code 128 與機器人權限問題

### ISSUE THREAD

**Issue by a31550277** [wdzeng/bot-automation#22]
`Action failed with "The process '/usr/bin/git' failed with exit code 128"` 是什麼問題？

**Comment by wdzeng** [comment]
1. 請仔細照著[使用說明](https://github.com/wdzeng/bot-automation/blob/main/docs/shopee-gha-inst.md)操作。
2. issue 內容請不要留空，否則很容易被誤認成垃圾訊息。
