### ISSUE TITLE
無法接收簡訊驗證

### ISSUE THREAD

**Issue by enjiang0423** [wdzeng/bot-automation#8]
您好，
在操作過程中，一直沒辦法收到蝦皮寄送的簡訊，稍早操作忘記密碼是能收到的，
請問是否有什麼方法可排除?
謝謝您。

**Comment by wdzeng** [comment]
您好，看了你的 log，發現簡訊沒有寄出去。我看不清原因。

想詢問一下您的密碼是否很短（少於八字）或很長（多於十六字）、是否有特殊符號呢？

**Comment by enjiang0423** [comment]
您好
1.密碼剛好8個字元
2.帳密是沒有符號或空格的
3.是的，是在台灣蝦皮註冊的

**Comment by wdzeng** [comment]
@enjiang0423 我剛剛更新了機器人原始碼，請再試一次。

**Comment by enjiang0423** [comment]
您好，
現在跑換出現1
Process completed with exit code 1.

**Comment by wdzeng** [comment]
@enjiang0423 請參考[這裡](https://github.com/wdzeng/bot-automation/issues/10#issuecomment-1159653350)，然後把截圖傳上來。感謝！

**Comment by akio-bob** [comment]
謝謝！

hyperbola ***@***.***> 於 2022年6月19日 週日 18:19 寫道：

**Comment by enjiang0423** [comment]
謝謝您。
看來應該是信箱驗證的。

**Comment by wdzeng** [comment]
了解。信箱驗證我需要一些時間開發，相關討論串我轉到 #12，先關掉這串囉。
