### ISSUE TITLE
想自己製作自己用的簽到機器人有參考資源嗎？

### ISSUE THREAD

**Issue by 0KHand** [wdzeng/bot-automation#9]
不好意思大大 小弟看到你的簽到機器人很感興趣，想要自己作一個別的網站的簽到Bot，不知道是否有可以參考整麼製作簽到Bot的教學資源？

**Comment by wdzeng** [comment]
關於網站的部分，因為前端不是我擅長的項目，我沒辦法給你參考。

關於 bot 的部分，我自己有兩份專案：

- [蝦皮簽到機器人](https://github.com/wdzeng/shopee-coins-bot)
- [Pinkoi 簽到機器人](https://github.com/wdzeng/pinkoi-coins-bot)

另外我推薦 @JacoLinCool 的 [巴哈簽到自動化！](https://github.com/JacobLinCool/Bahamut-Automation)，雖然我沒有用過，但感覺做得很棒。

**Comment by 0KHand** [comment]
了解 感謝大大回復
